Develop
frontend-park-mail-ru/2018_2_DeadMolesStudio pull request #2
Opened 2018-09-29 09:46 UTC by kirBMSTU

Некоторые компоненты, модули добавлены

2018-09-29 10:19 UTC, puchninanastya requested changes
В основном все отлично. Давайте доделываете шаблоны.

2018-09-29 10:19 UTC, puchninanastya commented on public/js/components/Button/Button.mjs
> +        <a href="${this._href}" class="cute-btn" data-href="${this._href}">
Значения лучше не хардкодить. Желательно сделать в таких случаях, как у вас в LinkComponent, с передачей в конструктор и значением по-умолчанию.

2018-09-29 10:19 UTC, puchninanastya commented on public/js/components/Menu/Menu.mjs
> +        Object.entries(this._titles).forEach( (entry) => {
titles можно сделать другим объектом. Почитайте про [Map](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map). Тогда вам намного проще будет по этому объекту делать перебор.

2018-09-29 10:19 UTC, puchninanastya commented on public/js/components/Scoreboard/Scoreboard.mjs
> +        switch (this._type) {
Вы это уберете потом?

2018-09-29 10:19 UTC, puchninanastya commented on public/js/index.js
> +            console.log(`linkTarget: ${event.target}`);
Надо разобраться, почему не работает, и пофиксить к рк.

2018-09-29 10:19 UTC, puchninanastya commented on public/js/index.js
> +    const titles = {
Вот про этот titles я говорила выше (Map).

2018-09-29 10:19 UTC, puchninanastya commented on public/js/modules/ajax.js
> +(function () {
Сделайте тоже в виде модулей с export.

2018-09-29 10:19 UTC, puchninanastya commented on public/js/index.js
> +    gameTitle.appendChild(h1);
У вас gameTitle не может быть не найден?

2018-10-01 05:25 UTC, puchninanastya commented on public/js/index.js
> +            if ( password !== passwordRepeat ) {
сравниваете не значения input'ов, а сами input'ы.
вечный not equals.

2018-10-01 06:37 UTC, kirBMSTU commented on public/js/index.js
> +            if ( password !== passwordRepeat ) {
пофиксил

2018-10-01 06:38 UTC, kirBMSTU commented on public/js/index.js
> +            console.log(`linkTarget: ${event.target}`);
Этот же компонент в ссылках под формами регистрации и логина работает правильно, даже callback такой же. Мистика. Будем разбираться

2018-10-01 09:14 UTC, kirBMSTU commented on public/js/components/Button/Button.mjs
> +        <a href="${this._href}" class="cute-btn" data-href="${this._href}">
Исправил

2018-10-01 09:14 UTC, kirBMSTU commented on public/js/components/Menu/Menu.mjs
> +        Object.entries(this._titles).forEach( (entry) => {
Исправил

2018-10-01 09:14 UTC, kirBMSTU commented on public/js/index.js
> +            console.log(`linkTarget: ${event.target}`);
исправлено благодаря нашему ментору)) виной тому innerHTML. Переделано на insertAdjacentHTML.

2018-10-01 09:14 UTC, kirBMSTU commented on public/js/modules/ajax.js
> +(function () {
Сделано

2018-10-01 14:13 UTC, merged